services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    command: npm run start:dev
    # command: npm run start:prod
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
